
/**
 * This file was generated by TONDev.
 * TONDev is a part of TON OS (see http://ton.dev).
 */
pragma ton-solidity >= 0.35.0;
pragma AbiHeader expire;

import "gameobj_interface.sol"; 

contract gameobj is gameobj_interface{

    int public _hp = 100;
    int public _deff = 0;
    address public _lastAddr;
    


    constructor() public {

        require(tvm.pubkey() != 0, 101);

        require(msg.pubkey() == tvm.pubkey(), 102);

        tvm.accept();

       
    }


    function getDeffStrength (int getdeff) virtual public {
        tvm.accept();

        _deff = getdeff;
    } 
    
    function getAttack (int getdmg) virtual external override  {
        tvm.accept();
        _hp = _hp - (getdmg - _deff);
        _lastAddr  = msg.sender;
        // am i dead?
        amIDead();
        
        
    }

    function amIDead () private{
        tvm.accept();
         if (_hp <= 0) {
            
            iAmDead(_lastAddr);

        }
    }

    function iAmDead (address dest) virtual public {
        tvm.accept();

        dest.transfer(1, false, 160);  


    }

    // держаться нету больше силь
    // и полтому я накатал костыль .-.

     function iAmDead2 (address dest) virtual public {
        tvm.accept();

        dest.transfer(1, false, 160);  
    }


}
